name: platty
description: Platform Conforming Widgets for Flutter!
version: 0.0.9+2
author: Andrew Grosner <andrew@fuzzproductions.com>
homepage: https://github.com/fuzz-productions/platty

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
